# from the sys-net checklist by tommy, forum.qubes-os.org topic 43535
# Only for Intel Cards, disable if no intel card
options iwlwifi p2p_disable=1

#if having realtek card, enable these:
#options rtw88_core disable_p2p=y
#options rtw89_core disable_p2p=y

#if having MediaTek card, enable this:
#options mt76_core disable_p2p=1

install bluetooth /bin/true
install btusb /bin/true
install btrtl /bin/true
install btintel /bin/true
install btbcm /bin/true
install pppoe /bin/true
install sctp /bin/true
install sctp_diag /bin/true
install atm /bin/true
install rds /bin/true
install cramfs /bin/true
install jffs2 /bin/true
install dccp /bin/true
install tipc /bin/true
install n-hdlc /bin/true
install ax25 /bin/true
install netrom /bin/true
install firewire-net /bin/true
install firewire-core /bin/true
install vivid /bin/true
